### ISSUE TITLE
About Docker and ROS

### ISSUE THREAD

**Issue by xavidzo** [darrenjkt/CenterPoint#1]
Hello @darrenjkt , you've done a wonderful job with the integration of CenterPoint in docker, congrats!
I have a question about what you wrote here:
> A Dockerfile that builds the ros environment to run ./tools/single_inference.py is included in this repo's branch ros. Just build and run in the same manner as the above. You can open another terminal and run your bag file there whilst you run the single_inference.py within the ros docker container.

So you mean the rosbag file can be run in another terminal, but I assume also inside the same container, right?
Or can you run the rosbag file outside the container (in the ROS environment of the host system) so that the single_inference.py within the container can subscribe to some topic outside and publish the detections also outside the container?
I hope, I explained myself clear, in short, I am asking if it's possible to enable communication between the ROS in the host and ROS inside the container.. do you know this?

Also, do I have to install nvidia-docker first to run your docker image? https://github.com/NVIDIA/nvidia-docker
Thanks in advance

**Comment by darrenjkt** [comment]
Yes there is communication between the ROS in the host, and ROS in the container. If you see the run.sh file, the ports are opened to host ( --net=host). This means that if you run roscore in either the container or host, it'll be the same roscore session. So yes, you can run single_inference.py in the container, and it'll be able to take input from a rosbag that is played outside the container. 

As for nvidia-docker, from memory I did have to install it for a few other packages I've been using but I have not checked if it's necessary for this specific repo.

**Comment by xavidzo** [comment]
Hello @darrenjkt, I have an issue not about CenterPoint, but about your project for camera-lidar calibration in https://gitlab.acfr.usyd.edu.au/its/cam_lidar_calibration, but I can't open an issue there, as I am not a student at your university.
Do you mind sharing your email address or some other form to contact you? I would really appreciate it, thanks in advance

**Comment by darrenjkt** [comment]
Hi @xavidzo yeah unfortunately since that repo is hosted on the university server there's a few restrictions on opening issues which is not ideal. You can reach me at d.tsai@acfr.usyd.edu.au
