### ISSUE TITLE
Failed to build docker

### ISSUE THREAD

**Issue by SuperPengXue** [darrenjkt/CenterPoint#3]
Hello @darrenjkt , you've done a wonderful job with the integration of CenterPoint in docker,but I got a error:
RUN curl -o ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
 ---> Running in 844fbefe34e8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /home/user/miniconda.sh: No such file or 
Warning: directory
  0 89.8M    0   900    0     0   1033      0 25:20:25 --:--:-- 25:20:25  1032
curl: (23) Failed writing body (0 != 900)

maybe my network limitation ！？  
could you upload the local docker image on google cloud.? thanks

**Comment by aldipiroli** [comment]
You can try changing 
`curl` into `wget -c` this should let you keep downloading even if the network fails.
